Metadata:
  License: Apache 2.0
Description:  'This template creates a role for running AWS Quickstart Helm and EKS cluster resource providers.
See https://github.com/aws-quickstart/quickstart-helm-resource-provide'

Resources:
  AWSQSHelmExecutionRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://wavelength-cloudformation-templates.s3.us-west-2.amazonaws.com/awsqs-helm-execRole.yaml
    
  AWSQSEKSExecutionRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://wavelength-cloudformation-templates.s3.us-west-2.amazonaws.com/awsqs-eksCluster-execRole.yaml

Outputs:
  AWSQSHelmExecutionRoleArn:
    Value: !GetAtt AWSQSHelmExecutionRole.Outputs.HelmExecutionRoleArn
  AWSQSEKSExecutionRoleArn:
    Value: !GetAtt AWSQSEKSExecutionRole.Outputs.AWSQSEKSExecutionRoleArn